build/test dynamic library in CI

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -392,3 +392,96 @@ jobs:
         run: "cc test-libbzip2-rs-sys/no_stdio.c -o no_stdio target/release/liblibbzip2_rs_sys.a -I ."
       - name: run C binary
         run: "./no_stdio | grep 'hello world!'"
+
+  link-c-dynamic-library:
+    name: vanilla dynamic library
+    strategy:
+      matrix:
+        include:
+          - target: x86_64-unknown-linux-gnu
+        features:
+          - ''
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+        with:
+          persist-credentials: false
+      - name: Install rust toolchain
+        uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248
+        with:
+          toolchain: stable
+          targets: ${{matrix.target}}
+      - name: "cdylib: default settings"
+        working-directory: libbzip2-rs-sys-cdylib
+        env:
+          LD_LIBRARY_PATH: "target/${{matrix.target}}/release/deps"
+        run: |
+          cargo build --release --target ${{matrix.target}}
+          cc -o bzpipe bzpipe.c target/${{matrix.target}}/release/deps/libbz2_rs.so -I ../
+          ./bzpipe < Cargo.toml | ./bzpipe -d > out.txt
+          cmp -s Cargo.toml out.txt
+      - name: "cdylib: rust-allocator"
+        env:
+          LD_LIBRARY_PATH: "target/${{matrix.target}}/release/deps"
+        working-directory: libbzip2-rs-sys-cdylib
+        run: |
+          cargo build --release --target ${{matrix.target}} --no-default-features --features="rust-allocator"
+          cc -o bzpipe bzpipe.c target/${{matrix.target}}/release/deps/libbz2_rs.so -I ../
+          ./bzpipe < Cargo.toml | ./bzpipe -d > out.txt
+          cmp -s Cargo.toml out.txt
+      #      - name: "cdylib: no_std"
+      #        env:
+      #          LD_LIBRARY_PATH: "target/${{matrix.target}}/release/deps"
+      #        working-directory: libbzip2-rs-sys-cdylib
+      #        run: |
+      #          cargo build --release --target ${{matrix.target}} --no-default-features
+      #          cc -o bzpipe_no_std bzpipe_no_std.c target/${{matrix.target}}/release/deps/libbz2_rs.so -I ../
+      #          ./bzpipe_no_std < Cargo.toml | ./bzpipe_no_std -d > out.txt
+      #          cmp -s Cargo.toml out.txt
+      - name: "cdylib: custom-prefix"
+        working-directory: libbzip2-rs-sys-cdylib
+        env:
+          LIBBZIP2_RS_SYS_PREFIX: "MY_CUSTOM_PREFIX_"
+        run: |
+          cargo build --release --target ${{matrix.target}} --features=custom-prefix
+          objdump -tT target/${{matrix.target}}/release/deps/libbz2_rs.so | grep -q "MY_CUSTOM_PREFIX_BZ2_bzCompressInit" || (echo "symbol not found!" && exit 1)
+
+  cargo-c-dynamic-library:
+    name: cargo-c dynamic library
+    strategy:
+      matrix:
+        include:
+          - target: x86_64-unknown-linux-gnu
+        features:
+          - ''
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+        with:
+          persist-credentials: false
+      - name: Install rust toolchain
+        uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248
+        with:
+          toolchain: stable
+          targets: ${{matrix.target}}
+      - name: Install cargo-c
+        env:
+          LINK: https://github.com/lu-zero/cargo-c/releases/download/v0.10.5
+        run: |
+          curl -L "$LINK/cargo-c-x86_64-unknown-linux-musl.tar.gz" |
+          tar xz -C $HOME/.cargo/bin
+      - name: build with and test the result of cargo-c
+        working-directory: libbzip2-rs-sys-cdylib
+        run: |
+          # build using cargo-c this time
+          cargo cinstall --release --destdir=/tmp/cargo-cbuild-libbzip2-rs # somehow --offline does not work here
+          tree /tmp/cargo-cbuild-libbzip2-rs
+          # verify that the SONAME  is set and includes a version
+          objdump -p target/x86_64-unknown-linux-gnu/release/libbz2_rs.so | awk '/SONAME/{print $2}' | grep -E 'libbz2_rs\.so\.1'
+          # build bzpipe with our library
+          cc -o bzpipe bzpipe.c -L/tmp/cargo-cbuild-libbzip2-rs/usr/local/lib/x86_64-linux-gnu -lbz2_rs -I ../
+          export LD_LIBRARY_PATH=/tmp/cargo-cbuild-libbzip2-rs/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
+          ./bzpipe < Cargo.toml | ./bzpipe -d > out.txt
+          cmp -s Cargo.toml out.txt
